title: Lucia Villegas Guerrero 
logo: Imagenes/300.jpg
description: Hi, welcome to my portfolio!

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
