title: Lucia Villegas Guerrero 
logo: Imagenes/1.jpg
description: Hi, welcome to my portfolio! 📩 lucia.villegas@pucp.edu.pe 🔗 LinkedIn

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
